<template>
  <main class="page">
    <section class="hero">
      <p class="eyebrow">Vue + Axum + Utoipa</p>
      <h1>Full-stack starter</h1>
      <p>
        Backend runs on Axum with autogenerated OpenAPI docs served from <code>/docs</code>.
        The frontend is powered by Vite + Vue and proxies API calls during local development.
      </p>
      <div class="greeting" v-if="!loading && greeting">
        <span class="label">Latest message</span>
        <strong>{{ greeting }}</strong>
      </div>
      <p v-if="loading">Fetching greeting…</p>
      <p v-if="error" class="error">{{ error }}</p>
    </section>

    <GreetingCard />
  </main>
</template>

<script setup>
import { onMounted, ref } from 'vue';
import GreetingCard from './components/GreetingCard.vue';
import { apiFetch } from './lib/apiClient.js';

const greeting = ref('');
const loading = ref(true);
const error = ref('');

const fetchGreeting = async () => {
  loading.value = true;
  error.value = '';

  try {
    const response = await apiFetch('/greeting');
    if (!response.ok) {
      throw new Error('Unable to contact backend');
    }

    const payload = await response.json();
    greeting.value = payload.message;
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Unknown error';
  } finally {
    loading.value = false;
  }
};

onMounted(fetchGreeting);
</script>

<style scoped>
.page {
  min-height: 100vh;
  padding: 4rem 1.25rem;
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
  gap: 2rem;
  background: radial-gradient(circle at top, #1d4ed8, #0f172a);
  color: #f8fafc;
  font-family: 'Inter', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
}

.hero {
  background: rgba(15, 23, 42, 0.75);
  border: 1px solid rgba(255, 255, 255, 0.12);
  border-radius: 1.25rem;
  padding: 2rem;
  box-shadow: 0 25px 65px rgba(15, 23, 42, 0.45);
}

.hero h1 {
  margin-top: 0.25rem;
  margin-bottom: 1rem;
  font-size: clamp(2rem, 4vw, 3rem);
}

.eyebrow {
  text-transform: uppercase;
  letter-spacing: 0.35em;
  font-size: 0.75rem;
  color: #cbd5f5;
}

.greeting {
  margin-top: 1.5rem;
  background: rgba(15, 23, 42, 0.6);
  border-radius: 0.75rem;
  padding: 1.5rem;
  border: 1px solid rgba(255, 255, 255, 0.08);
}

.greeting .label {
  font-size: 0.85rem;
  text-transform: uppercase;
  letter-spacing: 0.25em;
  color: #cbd5f5;
}

.error {
  color: #fca5a5;
  font-weight: 600;
}
</style>
